name: Automate tests before pushing branches

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Unit and Integration tests
        run: mvn clean verify
  
